### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [cloudwall/pytau#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.5.0. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary pytau -w /tmp/ext pytau==0.5.0
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting pytau==0.5.0
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/2a6/8c40f926848a5/pytau-0.5.0.tar.gz (6.1 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-0ol14ud1/pytau/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-0ol14ud1/pytau/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-0ol14ud1/pytau/pip-egg-info
         cwd: /tmp/pip-wheel-0ol14ud1/pytau/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-0ol14ud1/pytau/setup.py", line 9, in <module>
        with open('HISTORY.rst', 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by kyle-downey** [comment]
Fixed in 0.5.1
